language: r
cache:
- packages

addons:
  apt:
    packages:
      - libharfbuzz-dev
      - libfribidi-dev
      - libgit2-dev

r_packages:
- drat
- styler
- devtools
- pkgdown

before_cache:
- Rscript -e 'remotes::install_cran("pkgdown")'
- Rscript -e 'remotes::install_github("folkehelseinstituttet/org")'
before_install:
- bash travis/make.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis/drat.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && Rscript
  -e 'devtools::install(); pkgdown::build_site()'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_PAT"
  keep-history: true
  local-dir: docs
  on:
    branch: master
